language: android

android:
  components:
    - tools
    - platform-tools
    - android-28
    - build-tools-28.0.3
    - extra-android-m2repository

notifications:
  email:
      on_failure: change

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check
  - ./gradlew build
